const hexEditorTheme = {
    asciiPaddingX: 0,
    bytePaddingX: "0.1em",
    rowPaddingY: "0.1em",
    colorBackground: "var(--bg)",
    colorBackgroundEven: "var(--bg)",
    colorBackgroundCursor: "var(--hex-cursor-background)",
    colorBackgroundCursorHighlight: "var(--text-muted-inverted)",
    colorBackgroundColumnEven: "var(--bg)",
    colorBackgroundColumnOdd: "var(--header)",
    colorBackgroundInactiveCursor: "var(--hex-cursor-inactive-background)",
    colorBackgroundInactiveCursorHighlight:
        "var(--hex-cursor-inactive-background)",
    colorBackgroundInactiveSelection: "var(--hex-cursor-selection-background)",
    colorBackgroundInactiveSelectionCursor:
        "var(--hex-cursor-selection-background)",
    colorBackgroundLabel: "var(--bg)",
    colorBackgroundLabelCurrent: "var(--bg)",
    colorBackgroundOdd: "var(--header)",
    colorBackgroundRowEven: "var(--bg)",
    colorBackgroundRowOdd: "var(--header)",
    colorBackgroundSelection: "var(--hex-cursor-selection-background)",
    colorBackgroundSelectionCursor: "#61afef",
    colorScrollbackTrack: "var(--bg)",
    colorScrollbackThumb: "#495162",
    colorScrollbackThumbHover: "var(--text-muted-inverted)",
    colorText: "var(--text-muted)",
    colorTextEven: "var(--text-muted)",
    colorTextCursor: "var(--hex-cursor-highlight)",
    colorTextCursorHighlight: "var(--hex-cursor-highlight)",
    colorTextColumnEven: "var(--text-muted)",
    colorTextColumnOdd: "var(--text-muted)",
    colorTextInactiveCursor: "var(--hex-cursor-inactive-highlight)",
    colorTextInactiveCursorHighlight: "var(--hex-cursor-inactive-highlight)",
    colorTextInactiveSelection: "var(--text-muted)",
    colorTextInactiveSelectionCursor: "var(--text-muted)",
    colorTextLabel: "#495162",
    colorTextLabelCurrent: "#737984",
    colorTextOdd: "var(--text-muted)",
    colorTextRowEven: "var(--text-muted)",
    colorTextRowOdd: "var(--text-muted)",
    colorTextSelection: "var(--text-muted)",
    colorTextSelectionCursor: "var(--text)",
    fontFamily: "'Courier New', monospace",
    fontSize: "16px",
    gutterWidth: "0.5em",
    cursorBlinkSpeed: "0.5s",
    labelPaddingX: "0.5em",
    scrollWidth: "auto",
    textTransform: "uppercase",
};

export default hexEditorTheme;
